"""empty message

Revision ID: 111f9e174fa
Revises: 481796ed72c
Create Date: 2017-01-03 22:29:03.560253

"""

# revision identifiers, used by Alembic.
revision = '111f9e174fa'
down_revision = '481796ed72c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workitem_id'], ['workitems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasklogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasklogs')
    op.drop_table('tasks')
    ### end Alembic commands ###
