"""empty message

Revision ID: 1670b2d3b74
Revises: 4ddd78643b5
Create Date: 2017-01-08 13:50:52.428731

"""

# revision identifiers, used by Alembic.
revision = '1670b2d3b74'
down_revision = '4ddd78643b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasklogs', sa.Column('status_id', sa.Integer(), nullable=True))
    #op.drop_column('tasklogs', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklogs', sa.Column('status', sa.INTEGER(), nullable=True))
    op.drop_column('tasklogs', 'status_id')
    op.drop_table('taskstatus')
    ### end Alembic commands ###
