"""empty message

Revision ID: 1c2b915b8b5
Revises: 37f2b2fb136
Create Date: 2016-12-16 00:27:56.638075

"""

# revision identifiers, used by Alembic.
revision = '1c2b915b8b5'
down_revision = '37f2b2fb136'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('parent_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'parent_id')
    ### end Alembic commands ###
