"""empty message

Revision ID: 1d09e9261d5
Revises: 40d93619b7d
Create Date: 2016-12-16 11:38:41.336859

"""

# revision identifiers, used by Alembic.
revision = '1d09e9261d5'
down_revision = '40d93619b7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
