"""empty message

Revision ID: 270aca187e8
Revises: 111f9e174fa
Create Date: 2017-01-04 00:36:51.798977

"""

# revision identifiers, used by Alembic.
revision = '270aca187e8'
down_revision = '111f9e174fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('createdon', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'createdon')
    ### end Alembic commands ###
