"""empty message

Revision ID: 29634c8af15
Revises: 57b2f3574dd
Create Date: 2016-11-29 17:01:23.271770

"""

# revision identifiers, used by Alembic.
revision = '29634c8af15'
down_revision = '57b2f3574dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_data_link',
    sa.Column('workitem_id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['workitem_id'], ['workitems.id'], ),
    sa.PrimaryKeyConstraint('workitem_id', 'data_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_data_link')
    ### end Alembic commands ###
