"""empty message

Revision ID: 2a20a2921ec
Revises: 4e15cdb9cf0
Create Date: 2016-12-07 00:10:05.868901

"""

# revision identifiers, used by Alembic.
revision = '2a20a2921ec'
down_revision = '4e15cdb9cf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource_allocations', sa.Column('url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasource_allocations', 'url')
    ### end Alembic commands ###
