"""empty message

Revision ID: 2f917b799e3
Revises: 495f4e37846
Create Date: 2016-11-30 02:00:21.741254

"""

# revision identifiers, used by Alembic.
revision = '2f917b799e3'
down_revision = '495f4e37846'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_data_link')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_data_link',
    sa.Column('workitem_id', sa.INTEGER(), nullable=False),
    sa.Column('data_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['workitem_id'], ['workitems.id'], ),
    sa.PrimaryKeyConstraint('workitem_id', 'data_id')
    )
    ### end Alembic commands ###
