"""empty message

Revision ID: 36c71c9cab9
Revises: 3c11b1acbc
Create Date: 2016-11-29 11:20:34.083298

"""

# revision identifiers, used by Alembic.
revision = '36c71c9cab9'
down_revision = '3c11b1acbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operationsources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operationsources')
    ### end Alembic commands ###
