"""empty message

Revision ID: 40d93619b7d
Revises: 3d79893b26f
Create Date: 2016-12-16 11:32:52.368769

"""

# revision identifiers, used by Alembic.
revision = '40d93619b7d'
down_revision = '3d79893b26f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('workitems', 'parent_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workitems', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.drop_column('workflows', 'parent_id')
    ### end Alembic commands ###
