"""empty message

Revision ID: 45447e300f7
Revises: 36c71c9cab9
Create Date: 2016-11-29 11:25:22.278688

"""

# revision identifiers, used by Alembic.
revision = '45447e300f7'
down_revision = '36c71c9cab9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
