"""empty message

Revision ID: 481796ed72c
Revises: 1d09e9261d5
Create Date: 2016-12-17 16:56:40.351176

"""

# revision identifiers, used by Alembic.
revision = '481796ed72c'
down_revision = '1d09e9261d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
