"""empty message

Revision ID: 495f4e37846
Revises: 29634c8af15
Create Date: 2016-11-29 17:55:00.563979

"""

# revision identifiers, used by Alembic.
revision = '495f4e37846'
down_revision = '29634c8af15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
