"""empty message

Revision ID: 4ddd78643b5
Revises: 270aca187e8
Create Date: 2017-01-04 00:38:08.163193

"""

# revision identifiers, used by Alembic.
revision = '4ddd78643b5'
down_revision = '270aca187e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'createdon')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('createdon', sa.DATETIME(), nullable=True))
    op.drop_column('tasks', 'created_on')
    ### end Alembic commands ###
