"""empty message

Revision ID: 4e15cdb9cf0
Revises: 4fbf600aa07
Create Date: 2016-12-07 00:03:55.991225

"""

# revision identifiers, used by Alembic.
revision = '4e15cdb9cf0'
down_revision = '4fbf600aa07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasource_allocations')
    ### end Alembic commands ###
