"""empty message

Revision ID: 4fbf600aa07
Revises: 2f917b799e3
Create Date: 2016-12-06 07:18:40.061976

"""

# revision identifiers, used by Alembic.
revision = '4fbf600aa07'
down_revision = '2f917b799e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
