"""empty message

Revision ID: 5e25ef4e1d
Revises: 51f5ccfba190
Create Date: 2016-11-21 17:14:30.244595

"""

# revision identifiers, used by Alembic.
revision = '5e25ef4e1d'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
