"""empty message

Revision ID: bad49373d2
Revises: 4bccac39e00
Create Date: 2016-11-29 15:16:16.897216

"""

# revision identifiers, used by Alembic.
revision = 'bad49373d2'
down_revision = '4bccac39e00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_timestamp', 'workflows', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflows_timestamp', 'workflows')
    op.drop_table('workflows')
    ### end Alembic commands ###
